//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.Calculadora.Stub.Commom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Actions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Actions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS.Calculadora.Stub.Commom.Actions", typeof(Actions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Calculadora/divisao.
        /// </summary>
        internal static string Divisao {
            get {
                return ResourceManager.GetString("Divisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Server/GetServer.
        /// </summary>
        internal static string GetServer {
            get {
                return ResourceManager.GetString("GetServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Calculadora/multiplicacao.
        /// </summary>
        internal static string Multiplicacao {
            get {
                return ResourceManager.GetString("Multiplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Server/Remove.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Server/Inclui.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Calculadora/Alive.
        /// </summary>
        internal static string ServerAlive {
            get {
                return ResourceManager.GetString("ServerAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Calculadora/soma.
        /// </summary>
        internal static string Soma {
            get {
                return ResourceManager.GetString("Soma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Calculadora/subtracao.
        /// </summary>
        internal static string Subtracao {
            get {
                return ResourceManager.GetString("Subtracao", resourceCulture);
            }
        }
    }
}
